name: app_controle_tarefas
description: MVP de app de controlo de tarefas para contabilidade
publish_to: 'none'
version: 0.1.0+1


environment:
sdk: '>=3.3.0 <4.0.0'


dependencies:
flutter:
sdk: flutter
# Sem pacotes externos para manter simples


dev_dependencies:
flutter_test:
sdk: flutter
flutter_lints: ^4.0.0


flutter:
uses-material-design: true